### ISSUE TITLE
undefined: SecurityError

### ISSUE THREAD

**Issue by ilionic** [michaelcontento/redux-storage#117]
Getting following errors, possibly due local storage not being available in Safari private mode.

```
undefined: SecurityError: DOM Exception 18: An attempt was made to break through the security policy of the user agent.
```
```
QuotaExceededError: DOM Exception 22
```
![Alt text](https://dl.dropboxusercontent.com/u/101609037/Screenshot%202016-03-27%2014.15.08.png)

Maybe worth implementing extra check if localstorage is not available?

**Comment by Yuripetusko** [comment]
There is a shim solution floating around to check if window.localStorage is accessible, and if it is not, then replace it with memoryStorage, however according to other people it will not work, so instead of relying on window.localStorage it is better to abstract it into a wrapper and use that instead.

https://gist.github.com/daang77/fa08e4adc5277c2588f5

**Comment by michaelcontento** [comment]
The actual used storage engine is now decoupled from redux-storage. So feel free to use an existing engine (e.g. [redux-storage-engine-localstorage](https://github.com/michaelcontento/redux-storage-engine-localstorage)) as starting point for a new engine that serves your needs. Or provide a patch to [redux-storage-engine-localstorage](https://github.com/michaelcontento/redux-storage-engine-localstorage), if this can be solved in general for the localstorage engine 😄
