### ISSUE TITLE
[question] what are the pros and cons against redux-persist?

### ISSUE THREAD

**Issue by sibeliusseraphini** [michaelcontento/redux-storage#133]

**Comment by michaelcontento** [comment]
I'm not following the development on redux-persist but in it early days it was somewhat monolithic. But this might have changed ...

I started with redux-storage because I needed a very lightweight and simple way to persist my redux state. All existing solutions, at that time, where either to opinionated/big or missed some features and where not flexible enough. So redux-storage became alive and I tried to keep the core (aka redux-storage) as simple/small as possible. This is why all major features ([filtering](https://github.com/michaelcontento/redux-storage-decorator-filter), [immutablejs support](https://github.com/michaelcontento/redux-storage-merger-immutablejs), [debounce / batch save operations](https://github.com/michaelcontento/redux-storage-decorator-debounce) or different engine e.g. [react-native](https://github.com/michaelcontento/redux-storage-engine-reactnativeasyncstorage)) are separate projects. 

So if you want a small core and the ability to extend every aspect - redux-storage should be a good fit 😎 
Here a short overview of modules that can be used to configure different aspects of redux-storage:
* [engines](https://www.npmjs.com/browse/keyword/redux-storage-engine)
* [decorators](https://www.npmjs.com/browse/keyword/redux-storage-decorator)
* [mergers](https://www.npmjs.com/browse/keyword/redux-storage-merger)

I'll go ahead and close this issue to keep the list of open issues as short as possible. But feel free to re-open this issue if something is unclear or you simply want to discuss this further 😄
