### ISSUE TITLE
Race condition on Android with React Native

### ISSUE THREAD

**Issue by iheart2code** [michaelcontento/redux-storage#83]
Using the example code you provided, I get the following console log on iOS, where the app works just fine.

```
Running application "MyApp" with appParams: {"rootTag":1,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
action REDUX_STORAGE_LOAD @ 16:00:00.589
    prev state Object {initialLoad: false, currentUser: Object, entities: Object}
    action Object {type: "REDUX_STORAGE_LOAD", payload: Object}
    next state Object {initialLoad: true, currentUser: Object, entities: Object}
Loaded state: Object {}
```

But on Android, the storage loads immediately before the react native app starts up, causing some issues with waiting for the state to be loaded from disk. Here's the Android log.

```
action REDUX_STORAGE_LOAD @ 16:00:00.500
    prev state Object {initialLoad: false, currentUser: Object, entities: Object}
    action Object {type: "REDUX_STORAGE_LOAD", payload: Object}
    next state Object {initialLoad: true, currentUser: Object, entities: Object}
Loaded state: Object {}
Running application "MyApp" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
```

## Workaround
Rather than relying on `componentWillReceiveProps` to check if store has loaded, I'll make that check in both my `componentDidMount` and `componentWillReceiveProps` methods.

**Comment by michaelcontento** [comment]
I'd recommend using a reducer to keep track of the loaded-state and **not** in a component directly! With a custom reducer this flag is always present in the state and can be consumed by whatever component you want. Also there is no race condition, as the loader (created by `storage.createLoader`) requires your reducer function as argument.

Have a look [at this example](https://github.com/michaelcontento/redux-storage#actions), as it describes how to listen on the `LOAD` / `SAVE` action. 

If this does solve your question / issue, please close this thread. Otherwise keep on asking :smile:

**Comment by iheart2code** [comment]
@michaelcontento your suggestion is actually exactly what I ended up doing. Thanks!
